add event unsend & videoPlayComplete
moleike/line-bot-sdk pull request #5
Opened 2022-10-15 12:25 UTC by PamornT

add new event  unsend and videoPlayComplete

2022-10-15 13:32 UTC, moleike requested changes
Thanks for the patch 🙌
I left a couple of comments: we need to add some additional fields to make the event model consistent with the docs. Also, I renamed the constructors, so that they can be decoded correctly (look at the `FromJSON` instance for `Event`).

2022-10-15 13:32 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +  | UnSend            { source    :: Source
```suggestion
  | EventUnsend            { source    :: Source
```

2022-10-15 13:32 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +  | VideoPlayComplete { replyToken :: ReplyToken
```suggestion
  | EventVideoPlayComplete { replyToken :: ReplyToken
```

2022-10-15 13:32 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +  | VideoPlayComplete { replyToken :: ReplyToken
There is an additional field here, `videoPlayComplete.trackingId`.

2022-10-15 13:32 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +  | UnSend            { source    :: Source
There is also an additional field we'd need to add, `unsend.messageId`

2022-10-16 18:32 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +  | EventUnSend       { source    :: Source
```suggestion
  | EventUnsend       { source    :: Source
```

2022-10-16 18:33 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +data TrackingId = TrackingId
This could be a `newtype`

2022-10-16 18:34 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +  parseJSON = withObject "videoPlayComplete" $ \o -> do
```suggestion
  parseJSON = withObject "TrackingId" $ \o -> do
```

2022-10-16 18:34 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +                      , trackingId      :: TrackingId
```suggestion
                      , videoPlayComplete      :: TrackingId
```

2022-10-16 18:35 UTC, moleike reviewed
Left some comments.

2022-10-17 03:40 UTC, PamornT commented on src/Line/Bot/Webhook/Events.hs
> +                      , trackingId      :: TrackingId
Thank for suggest. It Done

2022-10-17 08:26 UTC, moleike commented on src/Line/Bot/Webhook/Events.hs
> +data TrackingId = TrackingId
```suggestion
newtype TrackingId = TrackingId
```

2022-10-17 08:28 UTC, moleike approved these changes

2022-10-17 08:28 UTC, merged